#!/usr/bin/env bash

# created this file to act as an answer file for the commands and steps used to pass task 2 of the MySQL project

# log in to your web-01 server and access MySQL
mysql -u root -p

# create the database
CREATE DATABASE E_corp;

# switch to newly created db
USE E_corp;

# create the nexus6 table
CREATE TABLE whtrose (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255));

# insert at least one entry [or two if you want :-)]
INSERT INTO nexus6 (name) VALUES ('Dennise');

# grant select permissions to holberton_user
GRANT SELECT ON E_corp.whtrose TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;

# verify the table and the entry we put in
SELECT * FROM whtrose;
