#!/usr/bin/env bash
# install the Uncomplicated Firewall (UFW) and setup a few rules on the web-01

sudo apt update -y

sudo apt install ufw -y

sudo ufw enable

sudo ufw default deny incoming -y
sudo ufw default allow outgoing -y

sudo ufw allow 22/tcp

sudo ufw allow 443/tcp

sudo ufw allow 80/tcp
